import type { Helplines } from "../services/types";
import { useT } from "../store/hooks";

/** Verified helpline numbers supplied by the server. Never generated by the model. */
export function SupportPanel({ helplines }: { helplines: Helplines }) {
  const t = useT();
  return (
    <aside role="region" aria-label={t("chat.support")} className="rise rounded-lg border border-line bg-alert-soft p-4 text-sm">
      <h3 className="font-medium text-alert">{t("chat.support")}</h3>
      <p className="mt-1">{helplines.message}</p>
      <ul className="mt-3 flex flex-col gap-2">
        {helplines.numbers.map((n) => {
          const first = n.number.split(" or ")[0].replace(/[^\d+]/g, "");
          return (
            <li key={n.name} className="flex flex-wrap items-baseline justify-between gap-x-3">
              <span>{n.name}</span>
              <span>
                <a className="font-medium text-alert underline" href={`tel:${first}`}>
                  {n.number}
                </a>
                <span className="ml-2 text-xs text-muted">{n.availability}</span>
              </span>
            </li>
          );
        })}
      </ul>
    </aside>
  );
}
